b_file: "bot.db"

bot_url: "https://t.me/ferestgo"
token: "telegram token"

messages:
  response:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    unknown_command: "Я не знаю такой команды :("
  error:
    default: "Произошла неизвестная ошибка."
    invalid_token:  "Неправильный токен авторизации"