name: remote ssh command
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
        script: |
              # Set env variables
              export token=${{ secrets.TELEGRAM_TOKEN }}

              cd /tg-balancer
              git pull
              go get -d ./...
              make build
              make run