name: remote ssh command
on: [push]

env:
  REGISTRY: "registry.digitalocean.com/sandbox-registry"
  IMAGE_NAME: "pocket-bot"
  CONTAINER_NAME: "pocket"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
        script: |
              # Stop running container
              docker stop $(echo $CONTAINER_NAME)

              # Remove old container
              docker rm $(echo $CONTAINER_NAME)

              # Set env variables
              export TOKEN=${{ secrets.TELEGRAM_TOKEN }}

              # Run a new container from a new image
              docker run -e TOKEN \
              --restart always \
              --publish 80:80 \
              --name $(echo $CONTAINER_NAME) \
              $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)