name: remote ssh start
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:      
    - name: build and run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
        script: |
              export token=${{ secrets.TELEGRAM_TOKEN }}

              cd tg-balancer
              git pull
              docker-compose up -d --build